### ISSUE TITLE
should have a way to name conditions

### ISSUE THREAD

**Issue by stephens999** [stephenslab/mashr#1]

**Comment by stephens999** [comment]
@gaow does mashr now respect the column names of bhat? Is it documented in a vignette? If so maybe you can close this?

**Comment by gaow** [comment]
I do not think I've changed the vignette but the names of bhat should be used. I'll make sure vignettes is up-to-date after #22 and close this issue then.

**Comment by gaow** [comment]
I do not think `ashr` respect column names -- because when I let simulation function generate bhat with conditions / effects , this unit test complains:

```
7. Failure: get same result as ash (@test_ash.R#23) ----------------------------
ashr::get_psd(m2)[, 1] not equal to ashr::get_psd(ashres).
names for target but not for current
```

So, should I revert my changes to simulation function or change unit test to make this pass, or to open a ticket in `ashr` like this one?
