### ISSUE TITLE
Error when df is a matrix

### ISSUE THREAD

**Issue by jmp448** [stephenslab/mashr#108]
Hello,

Thank you for the great software! I am running into an error in `mash_set_data` when df is a matrix. 

Reproducible example:
```
{library(mashr)
set.seed(1)
simdata = simple_sims(500,5,1)

df_mat = matrix(25, nrow=nrow(simdata$B), ncol=ncol(simdata$B))

data = mash_set_data(simdata$Bhat, simdata$Shat, df=df_mat)}
```

Error message:
`Error in if (!is.infinite(df)) { : the condition has length > 1`

I think this message used to be a warning in previous versions of R, and the first value would be used, but that still seems problematic in certain cases. I've created pull request #107 which I believe fixes this.

Session Info: 
> R version 4.2.0 (2022-04-22)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Scientific Linux 7.4 (Nitrogen)
> 
> Matrix products: default
> BLAS/LAPACK: /software/openblas-0.3.13-el7-x86_64/lib/libopenblas_haswellp-r0.3.13.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
>  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] mashr_0.2.57 ashr_2.2-54 
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.8.3     lattice_0.20-45  invgamma_1.1     mvtnorm_1.1-3    assertthat_0.2.1 truncnorm_1.0-8  grid_4.2.0       plyr_1.8.7      
>  [9] irlba_2.3.5      Matrix_1.4-1     rmeta_3.0        tools_4.2.0      softImpute_1.4-1 mixsqp_0.3-43    abind_1.4-5      compiler_4.2.0  
> [17] SQUAREM_2021.1

**Comment by pcarbo** [comment]
Thanks @jmp448!
