### ISSUE TITLE
Various questions

### ISSUE THREAD

**Issue by snaqvi1990** [stephenslab/mashr#17]
Hello,

Firstly thank you for this great tool. I have a couple of questions/issues. If it is easier I can also create new issues for each, but I'll just list them here for now. 

1) What is the best way to deal with "missing data" when using mashr? I.e., genes expressed in one tissues but not another. I have tried setting the betahat and sebetahat in those missing cases to 0, but then I get the following message when running mash: 

Error in (-npoint):0 : result would be too long a vector

For now, to circumvent this issue, I am only considering genes expressed in all tissues, but this ignores a lot of genes

2) In the canonical covariance matrices, what scenario does "simple_het_{1|2|3}" represent? I couldn't find a description of them in the preprint

3) The preprint mentions adding data-driven covariance matrices obtained through Sparse Factor Analysis, but the vignette doesn't mention this. Just wondering what's your guys' most up-to-date opinions on this.

4) minor point, but it would be convenient/nice if mashr could retain the row/column names of betahat and sebetahat. 

Thanks!
Sahin

**Comment by stephens999** [comment]
for missing data try setting the standard error to infinity not 0

**Comment by stephens999** [comment]
for 2, this should be in the ?cov_canonical help

**Comment by snaqvi1990** [comment]
Re: 1) and missing data: when I set the missing beta to 0 and missing SE to infinity and run mashr, I get the following:

error: chol(): decomposition failed
 - Likelihood calculations took 74.93 seconds.
 - Fitting model with 477 mixture components.
 - Model fitting took 8.63 seconds.
 - Computing posterior matrices.

error: inv_sympd(): matrix is singular or not positive definite
Error in calc_post_rcpp(t(data$Bhat), t(data$Shat), data$V, simplify2array(Ulist),  : 
  inv_sympd(): matrix is singular or not positive definite

**Comment by stephens999** [comment]
yes, thinking more about it this is not suprising. Try setting the missing SE to something "big".
choose something big compared with the other standard errors (10? 100?)

**Comment by snaqvi1990** [comment]
whoops, I think I deleted my earlier reply by accident. In any case, yes, setting missing SE to 10/100 (my max SE is 1.6 so these are big I suppose) works. I will play around with the exact SE to set, but for these relatively large SEs, the results are pretty invariant to changes in the missing SEs. Thanks!

**Comment by snaqvi1990** [comment]
update on this: while setting SE to large values allows mashr to run, I've found instances where the missing data instances have low LFSRs in the final output, presumably because they do have significant effects in other conditions. The results still make sense if I just ignore these instances, but this ultimately seems somewhat non-optimal

**Comment by stephens999** [comment]
I think it may be difficult to do better than this.

If the missing values are "missing at random" then this behavior seems entirely appropriate - 
even missing cases could have small lfsr based on the observed data at other conditions.

If they are not missing at random then it becomes hard to provide a general solution...
so the practitioner will have to decide whether to ignore them (as you suggest you feel
is appropriate for your data) or not.

**Comment by stephens999** [comment]
I'm closign this issue as dealt with
