### ISSUE TITLE
Option for EZ model

### ISSUE THREAD

**Issue by gaow** [stephenslab/mashr#22]
It does not seem from the main interface that we have an option to ask for the EZ model as used in the mash paper:

https://github.com/stephenslab/mashr/blob/master/R/mash.R#L26

Am I missing something? If not, then we should make this ticket a feature request.

**Comment by stephens999** [comment]
I checked. i think you are not missing anything - i did not implement this feature.

**Comment by gaow** [comment]
Here I propose an interface for the requested feature: we additionally add Z score to `set_mash_data`, 
```
set_mash_data = function(Bhat=null, Shat=null, Z=null, V=null) {
 if (is.null(Bhat) && is.null(Shat) && is.null(Z)) {
   stop("Please provide Bhat and Shat matrices, or Z matrix, or all three matrices.")
 }
 if (is.null(Bhat) && !is.null(Z)) {
   Bhat = Z
 }
 if (is.null(Shat)) {
  Shat = 1
 }
 if (is.null(V)) {
   V = diag(ncol(Bhat))
 }
  ...
 return(list(Bhat=Bhat, Shat=Shat, Z=Z, V=V))
}
```
Consequently:
1. `data := set_mash_data(...)`. If `data$Z` is not null we'll use `data$Z` for prior and mixture model steps, and report posterior in original scale. That is, providing `data$Z` essentially triggers EZ model.
2. We allow `data$Bhat` and `data$Shat` be `null` when `data$Z` is not null. That case we'll report posterior on Z-scale. Under the hood we simply set `data$Bhat` to `data$Z` and `data$Shat` to 1. 

Does this sound reasonable?

**Comment by stephens999** [comment]
I prefer to keep data as Bhat, Shat, and specify model used (EZ or not) when calling mash.

The data are the data. Don't want to confuse the data and the model.

In ash we have a parameter alpha that controls the model (EZ etc)

**Comment by gaow** [comment]
Okey ... but data is also relevant because we'll need to input Z score, unless we are cool setting it to `Bhat/Shat` -- is that what you suggest?

**Comment by gaow** [comment]
Just took a look at `ashr` code. Essentially it is also about `set_data` but is done inside `ash.workhorse`

https://github.com/stephens999/ashr/blob/master/R/ash.R#L335

So the "model" is also specified when data is initialized. In `ash` it is not called "model" either. Since `set_mash_data` is outside `mash` in `mashr`, we will have to "confuse" model with data if we do it the `ash` way.

@stephens999  what interface would you propose? Make `alpha` a parameter to `mash` function, and apply it after data is populated via `set_mash_data`? And by doing so, we'll have to use `Bhat/Shat` for z-score (which currently is not the case, as our z-score come from p-value of t-stats).

**Comment by stephens999** [comment]
Ok, so maybe the ashr interface is not best to copy in that regard!

**Comment by stephens999** [comment]
I think you raise a good point in t vs z scores. We could allow a df parameter to be specified in 'set_mash_data'. But I think there some questions on what models we are fitting because we can only actually got the normal likelihood, not t likelihood

**Comment by gaow** [comment]
> But I think there some questions on what models we are fitting because we can only actually got the normal likelihood, not t likelihood

So even though we have `df` we would still get a p-value and convert it to z-score ... and I think in that case `df` option make it conceptually even less clear (than my initial proposal that provides Z).

**Comment by gaow** [comment]
How about:

1. allow users to input `Z` with `set_mash_data`, optionally
2. add parameter `alpha` to `mash` call to specify choice of model -- just like in `ash`
3. add an additional, private function `reset_mash_data` to adjust data based on model choice. If `Z` was not provided, then we use `Bhat/Shat` to approximate it, with a warning message displayed.

**Comment by stephens999** [comment]
leave 1 for now. They can always set Bhat=Z and Shat = 1 if they want (for now).

2. sounds good

I dont' understand 3. I suspect we can use set_mash_data within `mash` to accomplish 2....

**Comment by gaow** [comment]
> I dont' understand 3. I suspect we can use set_mash_data within mash to accomplish 2....

3 would not make sense without 1. If we leave 1 for now we can use set_mash_data within `mash()`. But then there is no way to re-scale the effect size in posterior calculation because we've lost the Shat info -- this is what initialized this discussion.

**Comment by stephens999** [comment]
Here is my suggestion. We add a parameter `df` (matrix, or scalar if every entry is the same) to `set_mash_data`. 

Then internally we set Shat in mash data object to "Shat-effective" (Shat-eff) 
which is defined as follows:
Bhat/Shat-eff has the same p value under a z test as Bhat/Shat has under a t test with df degrees of freedom.

In other words, Shat-eff = Bhat/Z where Z is the Z score corresponding to a p value from a t test done on (Bhat,Shat,df)

If df =Inf then Shat-eff = Shat of course.

Then mash fits the model with likelihood Bhat \sim N(B, Shat-eff)
and prior Shat-eff^{-alpha} Bhat | Shat-effective \sim g()

**Comment by stephens999** [comment]
I could imagine it being useful to have an interface that provides the functionality that the user provides `Bhat` and a `pvalue` to `set_mash_data`, and we do a similar thing (work out an effective `Shat` value for them)

**Comment by gaow** [comment]
Ok so we essentially enhance `set_mash_data` without complicating it with model, and we use `alpha` at `mash` call to specify EZ model? I agree with providing `p-value`. I thought `df` is a bit misleading but I can see that effectively we are good after Shat-eff adjustment.

I guess now the only question remains is what happens if users did not provide `df` nor `p-value` but ask for EZ model?

**Comment by stephens999** [comment]
If they don't provide df I think default is to assume normal. Ie df infinity. But that is true whatever model they choose, not only EZ.
