### ISSUE TITLE
mash_set_data vs set_mash_data

### ISSUE THREAD

**Issue by stephens999** [stephenslab/mashr#28]
I feel we should switch this function to `mash_set_data` since it is more consistent with our
naming elsewhere (including in flashr for example)

I'm OK to have both functions, with one as an alias for the other?

**Comment by gaow** [comment]
In languages such as Python and C/C++ where the notion of namespace is more clear, we can just name it `set_data` and call via `mash.set_data` for Python, `mash::set_data` for C++. R is more sloppy with this. So manually add "namespace" as part of the function name, like `mash_set_data`, is perhaps the best option. It is a violation of some coding convention guideline that a function name should start with a verb, but in this context we all understand it is a compromise to R's design and we should not feel awkward about it. So I'm cool to keep solely `mash_set_data`.

**Comment by stephens999** [comment]
@gaow can you take care of this?
replace `set_mash_data` with `mash_set_data` 
make `set_mash_data` call `mash_set_data` but emit a warning that it is deprecated 
 and replace `set_mash_data` in vignettes

**Comment by gaow** [comment]
Good!
