### ISSUE TITLE
Write bottleneck computations in Rcpp

### ISSUE THREAD

**Issue by stephens999** [stephenslab/mashr#3]
@pcarbo I think this should be fairly straightforward. Maybe you can look into it?

I think we would want to implement:
`calc_lik_vector` and `calc_relative_lik_matrix` from https://github.com/stephenslab/mashr/blob/master/R/likelihoods.R
[note that strictly we probably only need implementations for log=TRUE if that helps]

`posterior_cov`, `posterior_mean` and `compute_posterior_arrays`
(maybe also the other functions) from
https://github.com/stephenslab/mashr/blob/master/R/posterior.R

**Comment by pcarbo** [comment]
The likelihood calculations should be relatively straightforward.

However, the `posterior_mean` and `posterior_cov` computations involve matrix computations; in those cases, there is relatively little to be gained by implementing them using Rcpp because R already uses fast routines for matrix operations. In `varbvs`, for example, all the matrix operations (multiplications, determinants, *etc*) are done in R.

**Comment by stephens999** [comment]
are you sure?
https://stackoverflow.com/questions/18349053/fastest-way-for-multiplying-a-matrix-to-a-vector

from memory (which is fallible, but consistent with the above link), 
when I looked at this, I also got faster performance using Rcpp.
Here is the code I used in fast-ash
(https://github.com/stephenslab/fast-ash/blob/master/analysis/mmult.cpp)
```
// this multiplies columns of matrix m, between rows a and b, by vector v
// [[Rcpp::export]]
NumericMatrix my_mmult(const NumericMatrix & m ,const NumericVector & v , int a, int b){

  if( ! (m.ncol() == v.size()) ) stop("Non-conformable arrays") ;
    
  NumericMatrix out(b-a+1 , m.ncol()) ;
  
  for (int j = 0; j < m.ncol(); j++) {
    for (int i = 0; i < b-a+1; i++) {
      out(i,j) = m(i+a,j) * v[j];
    }
  }
  
  return out ;
}
```

**Comment by pcarbo** [comment]
@stephens999 Your example isn't matrix multiplication, but I would be shocked if Rcpp can do better than BLAS. I'll cook up an empirical comparison.

**Comment by pcarbo** [comment]
@stephens999 I implemented a [small R script](https://github.com/pcarbo/pcarbo/blob/master/R/demo.multiply.R) to compare standard matrix-vector multiplication in R. This is the result I obtained on my MacBook Pro:

```R
> source("demo.multiply.R")
# Generating data.
# Computing A x b using base.
# Computing A x b using Matrix package.
# Computing A x b using Rcpp.
#                            expr    min     lq   mean median     uq    max neval
# base           x1 <- c(A %*% b) 0.3523 0.3617 0.3897 0.3729 0.4018 0.6140   100
# Matrix x2 <- as.vector(M %*% b) 0.1815 0.1884 0.2028 0.1974 0.2124 0.2795   100
# Rcpp         x3 <- mymult(A, b) 1.2876 1.3441 1.4255 1.3889 1.4421 2.4297   100
```

So actually the `Matrix` package is fastest, with a roughly 7x speedup over Rcpp.

I'm sure there are non-standard matrix operations that could be implemented faster in `Rcpp`, but almost all common matrix-vector operations, and solving linear systems, should be computed using optimized versions of BLAS and LAPACK (e.g., Accelerate in Mac OS X)---they are very, very hard to beat. (They have been developing these algorithms for >30 years.)

**Comment by stephens999** [comment]
thanks for checking this - it is good to know

**Comment by gaow** [comment]
Converged to #4
