### ISSUE TITLE
Optimizing matrix calculations

### ISSUE THREAD

**Issue by gaow** [stephenslab/mashr#4]
@kkdey and I were looking at issues running `mashr` on an input of size 16K * 53 via canonical covariance matrix. Long story short is that for data of this scale we need to re-engineer calculations after `mixIP` stage. The longer version goes with this code to reproduce what we've seen:

```r
library(mashr)
data <- get(load("death_time_cor_nonmash.rda"))
betahat <- data$betahat
sebetahat <- data$sebetahat
mash_data <- set_mash_data(t(betahat), t(sebetahat))
U.c = cov_canonical(mash_data)
print(names(U.c))
#############  canonical mash performance ###############
cat("starting the canonical mash \n")
m.c = mash(mash_data, U.c)
save(m.c, file = "mash_circadian_canonical.rda")
```
Computational resource footprint of 3 stages of `mash` function (1. before `mixIP`, 2. `mixIP` and 3. after `mixIP`) are:

1. 100% CPU, under 0.5GB memory, about 2hrs computation. So far so good
2. 1992% CPU, under 2.5GB memory, not very long computation. So far so good
3. Back to 100% CPU, but memory starts to grow rapidly to about 45GB before R complains and quits on:

```
Error: cannot allocate vector of size 10.7 Gb
Execution halted
Warning message:
system call failed: Cannot allocate memory 
```
Here is the data used. 
[mwe.tar.gz](https://github.com/stephenslab/mashr/files/1056552/mwe.tar.gz)

@pcarbo it requires 50GB memory and a few hours computation to reproduce the problem. We can possibly get around the issue by changing system `ulimit` but the computational resource footprint is a bit daunting as is. Working at 53 conditions (if this is the culprit??) is the current requirement of GTEx. I'm submitting this here now and we can revisit it for a fix. 

Maybe we'll have to revisit #3 from this aspect ...

**Comment by gaow** [comment]
@pcarbo another test is perhaps to book a huge memory node from RCC, set `ulimit` to some infinite value, and see how much memory it actually uses (assuming `ulimit` can fix the complaint from R)?

**Comment by pcarbo** [comment]
Thanks @gaow @kkdey for looking into this issue. Can you provide me with the commit id of the `mashr` repository you used, and post the output of running `sessionInfo()`?

Also, could you create a similar example that could conceivably run on a laptop (e.g., with maximum memory usage of 4 GB)? This will be more convenient for me for working through the code on my computer. Thanks.

**Comment by gaow** [comment]
Sure @pcarbo the commit id is 126fd031718bccaf976a8d904fe4ca57e2bde97f and session info:
```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: BunsenLabs GNU/Linux 8.7 (Hydrogen)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mashr_0.1-6

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11             lattice_0.20-35          codetools_0.2-15        
 [4] mvtnorm_1.0-6            foreach_1.4.3            assertthat_0.2.0        
 [7] truncnorm_1.0-7          MASS_7.3-47              grid_3.3.2              
[10] ExtremeDeconvolution_1.3 pscl_1.4.9               doParallel_1.0.10       
[13] Matrix_1.2-10            rmeta_2.16               iterators_1.0.8         
[16] parallel_3.3.2           ashr_2.1-19              SQUAREM_2016.8-2    
```
I think perhaps we can start with this setting below and see how it works on your laptop? eg:

```
data$betahat = data$betahat[1:2,1:1000]
data$sebetahat = data$sebetahat[1:2,1:1000]
```
This computation is trivial and takes less than 1min on my computer. I guess you can scale it up as you see fit until the problem is more evident to observe?

**Comment by stephens999** [comment]
the large memory assignments that I am aware of are in 
`compute_posterior_arrays`. 
Do you think this is the problem? Can you tell at what line the assignment is failing?

We are assigning 5 large arrays in this function.
``
post_mean=array(NA,dim=c(J,P,R))
  post_mean2 = array(NA,dim=c(J,P,R)) #mean squared value
  post_var = array(NA,dim=c(J,P,R)) #mean squared value
  #post_pos=array(NA,dim=c(J,P,R))
  post_zero=array(NA,dim=c(J,P,R))
  post_neg=array(NA,dim=c(J,P,R))
``

J is 16k, R is 53, P is the number of covariance matrices (= grid length * number of Uk = L*K).
I think K is about 60 here, and maybe L is about 20? 
If so that would give 10^9 entries per array, and if we have 8 bytes per entry then we have
8 Gb per array, or 40Gb total.

This is just back of the envelope... it seems conceivable this is the root of the problem.

Some potential solutions:
- reduce P by pruning away negligible components
- do the calculations in batches of smaller J (calculations are independent for each J)

**Comment by stephens999** [comment]
actually the obvious solution is to do the computations one effect at a time (ie for j=1,\dots, J).
So that you never need the J by P by R arrays.

**Comment by gaow** [comment]
I think your back of the envelope calculation is consistent with what I've observed; and your suggestion seems good idea if it is not significantly slower. I can take a look tomorrow if @pcarbo does not have a chance to fix it today :)

**Comment by stephens999** [comment]
great!

**Comment by pcarbo** [comment]
@gaow @stephens999 I think it might be helpful to think more strategically about how to (1) reduce memory requirements, and (2) speed up the computations since I'm assuming Gao will soon want to apply `mashr` quickly to large data sets. (See also Issue #3.)

As a starting point, I created a new branch `dev`, and a script `test_mashr.R` which we can use to profile computation (memory + time) using the data set Gao provided. Here's an example output on my MacBook Air:

```
> source("test_mashr.R")
Loading data.
Generating covariance matrices.
 [1] "identity"      "singletons_1"  "singletons_2"  "singletons_3"
 [5] "singletons_4"  "singletons_5"  "equal_effects" "simple_het_1"
 [9] "simple_het_2"  "simple_het_3"
Running mash analysis.
 - Computing 1000 x 211 likelihood matrix.
 - Likelihood calculations allocated 16.65 MB and took 139.93 seconds.
 - Fitting model with 211 mixture components.
 - Model fitting allocated 11.54 MB and took 0.83 s.
 - Computing posterior matrices.
 - Computation allocated 151.86 MB and took 114.65 seconds.
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
[1] profmem_0.4.0    mvtnorm_1.0-6    ashr_2.1-19      rmeta_2.16
[5] assertthat_0.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11      lattice_0.20-34   codetools_0.2-15  Rmosek_7.1.3
 [5] foreach_1.4.3     truncnorm_1.0-7   MASS_7.3-45       pscl_1.4.9
 [9] doParallel_1.0.10 Matrix_1.2-8      iterators_1.0.8   REBayes_0.73
[13] parallel_3.3.2    SQUAREM_2016.8-2
```

**Comment by gaow** [comment]
Thank you @pcarbo. A more strategic approach would benefit the long run than a monkey patch from a couple of hours coding. I too want to see how we can improve speed stage 1&3. Looking forward to discussing it in person tomorrow!

**Comment by gaow** [comment]
In general there are two type of improvements we can do: 1) improve the code and 2) improve the formulation / math.

Yesterday @stephens999 pointed out to me the speed bottle-neck in likelihood calculation and discussed possible ideas for 2) focusing on inverse calculation. Today @pcarbo and I re-discussed that conversation. We think even if we can improve the inverse part, there are still potentially millions of matrix multiplications that can be very time consuming to do in R. An obvious speed up maybe related to #3 to handle all these loops. Therefore we decide to re-implement likelihood calculation in C++ without thinking about the math for now, see how much we gain, then work on the math as a next step.

For this task we decide:

1. First draft a naive / native C++ Armadillo implementation for likelihood, first for one `j,k,l`, to ensure the correctness, then test how much speed gain we have with the loop.
2. Then look into parallel computation (with `openmp`).
3. Figure out the most efficient way to interface with C++ codes (possibly via RcppArmadillo?) and an easiest way to make sure `mashr` installs smoothly (`openmp` flag could potentially be an issue).
4. Then move on to converting posterior calculations

I'll take a stab on the draft implementation while @pcarbo figures out the best way to communicate and embed these libraries in `mashr`. Once we've figured out these more fundamental changes & infrastructure the rest of the work on changing the math, making parallel and migrating posterior calculation can be done in parallel as we wish.

**Comment by pcarbo** [comment]
Thanks @gaow. I think that is a good summary. Note: I thought we decided that the order was 1, 4, 2, 3.

To clarify, my general impression is that the likelihood calculations are O(n^3), where n is the number of phenotypes/conditions. A more clever reuse of calculations could hypothetically reduce this to O(n^2), so a reduction in a factor of O(n). I think that starting with a C++ implementation will get us a bigger gain in speed, so I thought it would be better to start with this first, especially since this gain in speed will be irrespective of the number of phenotypes/conditions. These can be seen as complementary improvements, so we can ultimate try both.

**Comment by gaow** [comment]
I've implemented the likelihood calculation in C++/Armadillo. For `test_mash.R` the computational time of likelihood calculation reduced from 37.07 sec to 0.35 sec, a 100 times speed improvement and 50% memory usage! The result agree at least on this data-set. Note that we have not used openmp: we may gain more if we do.

```
[GW] Rscript test_mashr.R 
Loading required package: grid
Loading data.
Generating covariance matrices.
 [1] "identity"      "singletons_1"  "singletons_2"  "singletons_3" 
 [5] "singletons_4"  "singletons_5"  "equal_effects" "simple_het_1" 
 [9] "simple_het_2"  "simple_het_3" 
Running mash analysis.
 - Computing 1000 x 211 likelihood matrix.
 - Likelihood calculations allocated 16.79 MB and took 37.07 seconds.
 - Computing 1000 x 211 likelihood matrix in C++.
 - Likelihood calculations via Armadillo allocated 8.40 MB and took 0.35 seconds.
[1] "Is result equal between R and C++?" "TRUE"                              
 - Fitting model with 211 mixture components.
 - Model fitting allocated 0.05 MB and took 0.01 s.
 - Computing posterior matrices.
 - Computation allocated 151.89 MB and took 33.45 seconds.
Error in lm$lik_matrix %*% pi : non-conformable arguments
Calls: system.time -> mash -> compute_loglik_from_matrix_and_pi
Timing stopped at: 71.224 0.092 71.257 
```

@pcarbo I'm not sure why there is an error message in the bottom but this is not relevant to the changes I made today (I see the same at this version too: ac5f7efd2d9996b77c182ae99effa5c7b7463d52). Perhaps we need to  fix it in order to compare results when we replace posterior calculations.

**Comment by gaow** [comment]
Oh @pcarbo in order to reproduce my new code you need to pull from `dev`, then run `make` to build / install the package. You can look at the `Makefile` and decide what is the best way to distribute it via `install_github()`. Also `src/utils.hpp` is the workhorse in C++; the `src/main.cpp` is the Rcpp interface, and the entire armadillo library was copied to `src/include` without any customizations.

**Comment by stephens999** [comment]
wow! that is impressive.

I spent the evening trying to see how math could help.
I came to the following conclusion.

We need to compute normal likelihoods under covariance matrices
(w_l U_k + V_j) where U_k and V_j are R by R matrices and w_l is a scalar.
[l =1,\dots,L; k=1,\dots,K; j=1,\dots,p]

The naive calculation is o(R^3) for each l,k,j combination, so total
is LKpR^3

i) in the general case (general error variance V_j for each observation j)
we can't save very much. By solving a generalized eigenvalue problem
for each (j,k) combination we should be able to avoid doing the
R^3 decomposition separately for each l. That is we might
reduce to o(KpR^3 +  LKpR^2) or something like that.
However, I'm skeptical we would end up achieving an L fold speed-up.
There would be constants involved, and it would require adding
quite a bit of complication to the code that might be harder to maintain.
I'm not at all convinced it is worth it.

ii) in the special case where V_j is the identity for all observations
(maybe
when fitting mash to Z scores) we could likely save a lot more -
I believe we could
do the R^3 calculation only for the K U_k matrices by eigen-decomposition,
and then everything else to be R^2. That is we would have o(KR^3 +
 LKpR^2).

It is possible this could be worth implementing as a special
case at some point. However, not priority.

This is helpful:

https://math.stackexchange.com/questions/1747812/inverse-of-the-sum-of-a-invertible-matrix-with-known-cholesky-decomposion-and-di
specifically the second answer

**Comment by pcarbo** [comment]
@gaow Great work! Yesterday, I predicted a 100x speedup, so I was pretty close! :) I will look at your implementation on Monday. I will also look into converting your code to `Rcpp` + `Armadillo` from `RcppArmadillo` (if it is indeed useful to do so).

@stephens999 I agree with your general assessment. One other consideration is that we may decide to make changes the model depending on the GTEx results. Investing a lot of time in speeding up calculations is better to do after we are more certain that the model we are using is the right one. :)

**Comment by gaow** [comment]
Thank you @stephens999 and @pcarbo. I've also computed posterior in C++ -- perhaps not the most efficient coding (direct inverse used, also not happy with my vector version of normal CDF) but via `test_mash.R` the computation time dropped from 46 sec to 0.7 sec, and the memory dropped from 147.05MB to 2.78MB. See below:

```
Loading required package: grid
Loading data.
Generating covariance matrices.
 [1] "identity"      "singletons_1"  "singletons_2"  "singletons_3" 
 [5] "singletons_4"  "singletons_5"  "equal_effects" "simple_het_1" 
 [9] "simple_het_2"  "simple_het_3" 
Running mash analysis.
 - Computing 1000 x 211 likelihood matrix.
 - Likelihood calculations allocated 16.79 MB and took 48.66 seconds.
 - Computing 1000 x 211 likelihood matrix in C++.
 - Likelihood calculations via Armadillo allocated 8.40 MB and took 0.45 seconds.
[1] "Is result equal between R and C++?" "TRUE"                              
 - Fitting model with 211 mixture components.
 - Model fitting allocated 11.90 MB and took 0.40 s.
 - Computing posterior matrices.
 - Computation allocated 147.05 MB and took 46.11 seconds.
 - Computing posterior matrices in C++.
 - C++ Computation allocated 2.78 MB and took 0.70 seconds.
[1] "Is result equal between R and C++?" "TRUE" 
```

So we may benefit a lot from this simple code conversion. @pcarbo please check `src/main.cpp` and suggest how we can perhaps utilize `RcppArmadillo` better. Currently I had to "reshape" a 3D array (or map the memory to it) but there may be easier ways to communicate? Also I've put a couple of `FIXME` in `src/utils.hpp` to get your attention when you review it. 

I think the next steps are 1) code review and better interfacing, 2) implement parallel version, and 3) change the math based on @stephens999 suggestion if we are still not happy by then.

**Comment by stephens999** [comment]
@gaow do you think this is done?
