### ISSUE TITLE
error: chol() decomposition failed

### ISSUE THREAD

**Issue by lukeholman** [stephenslab/mashr#42]
Sometimes when running mash, it prints this error to the console hundreds of times, yet mash seems to finish just fine and produce an apparently sensible output. As a new user it's unclear if I should worry about this or what causes it, and ideally I'd just like one error message! Can post more data and code later, assuming you haven't seen this already?

**Comment by lukeholman** [comment]
Ahhh this error occurs when feeding `mash()` a canonical matrix that is not acceptable. Due to a typo I had passed it a matrix that is not "positive definite" or whatever you call it, like this:

    matrix(c(rep(1,8), rep(0,8)), nrow = 4, ncol = 4)

Maybe an extra input check to guard against user error?

**Comment by stephens999** [comment]
thanks @lukeholman - good idea! can you provide a minimal reproducible example so we can test we fix your specific case?

**Comment by pcarbo** [comment]
@stephens999 I think the example he gave above is sufficient, although if I understand correctly, a matrix need not be positive definite (e.g., the matrix of all ones), but it does need to be positive semi-definite? @lukeholman Your matrix here is not symmetric, which is the main issue.

@gaow Do we currently have any checks for the `Ulist` argument?

**Comment by stephens999** [comment]
I agree that I think I understand the problem.  But I would still like an
example!
It is a good practice.... one sometimes guesses wrong about what a users
problem is.

**Comment by lukeholman** [comment]
Sure, here's an example:

    set.seed(1)
    simdata <- simple_sims(500,5,1)
    U.bad <- list(matrix(c(rep(1,10), rep(0,10)), nrow = 5, ncol = 5))
    m.c <- mash(mash_set_data(simdata$Bhat, simdata$Shat), U.bad)

FYI I'm pretty sure I have also seen it when using ED matrices, which should not be asymmetric

**Comment by pcarbo** [comment]
@gaow Any updates on this Issue? I made some recommendations on Slack. I can post them here if that would be more convenient.

**Comment by pcarbo** [comment]
@gaow I'm having trouble understanding how you implemented the check for a spd matrix, but it isn't stopping when I provide an indefinite matrix. Here's an example:

```R
library(mashr)
set.seed(1)
simdata <- simple_sims(500,5,1)
U.bad <- matrix(c(rep(1,10), rep(0,10)), nrow = 5, ncol = 5)
U.bad <- U.bad + t(U.bad)
m.c <- mash(mash_set_data(simdata$Bhat, simdata$Shat), list(U.bad))
```

**Comment by gaow** [comment]
@pcarbo i think we agreed to allow for indefinite matrix.

**Comment by pcarbo** [comment]
@gaow You're right. So this is a different issue, because this is the output I get when running this example:

```
 - Computing 2000 x 16 likelihood matrix.
error: chol(): decomposition failed
error: chol(): decomposition failed
error: chol(): decomposition failed
error: chol(): decomposition failed
error: chol(): decomposition failed
error: chol(): decomposition failed
 - Likelihood calculations took 0.01 seconds.
 - Fitting model with 16 mixture components.
 - Model fitting took 0.18 seconds.
 - Computing posterior matrices.
 - Computation allocated took 0.01 seconds.
```

So looks like you need to suppress the `chol` error messages.

**Comment by stephens999** [comment]
My suggestion was not to bother checking for this case (symmetric and square, but not a covariance matrix) because it seems pretty far fetched. The chol errors seem enough to me. But we should not suppress them! Either leave them and say this is good enough check, or put in a more thorough try catch and exit.

**Comment by pcarbo** [comment]
@gaow @stephens999 Apologies, again I was not thinking clearly about this error. 

Looking in to this error more carefully, I think that this example is useful  as it may point to a bug in the likelihood computation code---perhaps this is a bug that would only occur in "edge" cases, which is why we had not  encountered it before.

I modified the example above slightly to use the R likelihood computation code:

```
library(mashr)
set.seed(1)
simdata <- simple_sims(500,5,1)
U.bad   <- matrix(c(rep(1,10), rep(0,10)), nrow = 5, ncol = 5)
U.bad   <- U.bad + t(U.bad)
m.c     <- mash(mash_set_data(simdata$Bhat, simdata$Shat), list(U.bad),
                algorithm.version = "R")
```

What I found, in this example, is that the last 6 covariance matrices from the conditional likelihood---that is, `V + Ulist[[i]]` with i from 11 to 16 in function `calc_lik_matrix_common_cov`---are not positive definite, so `dmvnorm` when provided with a non-spd matrix simply returns `-Inf`. What is needed here is a check for positive definiteness of the covariance matrix supplied to `dmvnorm`. And if that check fails, I'm guessing we should stop and report an error?

**Comment by gaow** [comment]
@pcarbo that is what I'm saying that "we need a check down the line", but I'm not sure about "where" down the line. If we check and quit, it may make more sense to check `V + w_lU_k` (or maybe `V + U_k` is enough?) for PSD and quite before feeding into `dmvnorm`. Otherwise we can just wrap that error message to a nicer one and let it continue.

**Comment by pcarbo** [comment]
@gaow I believe this is where the error first occurred, so this seems like the right place to check.

**Comment by stephens999** [comment]
To me I am not convinced this is worth our time. Chol already correctly
reports the error. And in the worst case where the user ignores the error
these matrices are ignored because they produce -inf likelihood.

**Comment by pcarbo** [comment]
I didn't meant it to be complicated. I pushed the suggested improvement, which now outputs a warning when some columns of the likelihood matrix have non-finite values:

``` - Computing 2000 x 16 likelihood matrix.
 - Likelihood calculations took 0.03 seconds.
 - Fitting model with 16 mixture components.
 - Model fitting took 0.03 seconds.
 - Computing posterior matrices.
 - Computation allocated took 0.04 seconds.
Warning message:
In calc_lik_matrix(data, Ulist, log = TRUE, algorithm.version = algorithm.version) :
  Some mixture components result in non-finite likelihoods, either
 due to numerical underflow/overflow, or due to covariance matrices
 that are not s.p.d.: 11, 12, 13, 14, 15, 16
```

@gaow Feel free to revise my code.

@gaow I also adjusted the dmvnorm calls in the R code to make sure that non-spd matrices result in `-Inf` likelihoods, although not sure that was necessary. It looks like the Rcpp code also gives `-Inf` appropriately, but you may want to double-check this.

@gaow With this warning, I think it is safe to supress the `chol` error messages.

**Comment by lukeholman** [comment]
Hey there, just reaffirming that I very often get this chol() warning when running mashr using matrices generated by `cov_ed` (following the 2nd vignette). Maybe these matrices can end up non-SPD sometimes? 

Here are the matrices I'm putting in: NB that printed warning message that `cov_ed` caused a decrease in log likelihood. As a naive user, I am not sure what this message is telling me. Maybe that the matrices produced by ED provide a worse fit to the data than the ones in `U.pca` (which I generated using `cov_pca`)? Might be worth updating this warning message or the `?cov_ed` text to be more idiot proof. 

I guess the problem here might be that the 4th matrix has negative numbers on the diagonal, meaning it is not a real covariance matrix (since variance cannot be negative)?

```
> U <- cov_ed(mash_data, U.pca, subset = strong)
Warning: log likelihood decreased by -0.0419145

> U
$ED_PCA_1
             [,1]          [,2]          [,3]          [,4]
[1,]  0.023652466  0.0174947393 -1.503344e-03 -1.061791e-03
[2,]  0.017494739  0.0129401263 -1.111961e-03 -7.853621e-04
[3,] -0.001503344 -0.0011119610  9.555217e-05  6.748713e-05
[4,] -0.001061791 -0.0007853621  6.748713e-05  4.766519e-05

$ED_PCA_2
             [,1]         [,2]        [,3]        [,4]
[1,] 0.0002221886 1.352712e-04 0.003679627 0.001968462
[2,] 0.0001352712 8.235475e-05 0.002240203 0.001198424
[3,] 0.0036796272 2.240203e-03 0.060937679 0.032599363
[4,] 0.0019684620 1.198424e-03 0.032599363 0.017439431

$ED_PCA_3
              [,1]          [,2]          [,3]          [,4]
[1,]  1.759228e-08  3.975776e-07 -1.537631e-05  2.871348e-05
[2,]  3.975776e-07  8.985077e-06 -3.474977e-04  6.489118e-04
[3,] -1.537631e-05 -3.474977e-04  1.343910e-02 -2.509597e-02
[4,]  2.871348e-05  6.489118e-04 -2.509597e-02  4.686382e-02

$ED_PCA_4
              [,1]          [,2]          [,3]          [,4]
[1,] -0.0358440681  0.0484880393  5.668877e-04 -3.596554e-04
[2,]  0.0484880393 -0.0655921629 -7.668570e-04  4.865235e-04
[3,]  0.0005668877 -0.0007668570 -8.965547e-06  5.688088e-06
[4,] -0.0003596554  0.0004865235  5.688088e-06 -3.663634e-06

$ED_tPCA
             [,1]         [,2]         [,3]         [,4]
[1,]  0.050167549  0.036522732 -0.003341573 -0.004320626
[2,]  0.036522732  0.027562714 -0.003038328 -0.003495533
[3,] -0.003341573 -0.003038328  0.030477025  0.015587493
[4,] -0.004320626 -0.003495533  0.015587493  0.009934491
```

And here are the messages generated by mash when it finished printing the chol() errors. 

```
- Likelihood calculations took 3.52 seconds.
 - Fitting model with 76 mixture components.
 - Model fitting took 1.63 seconds.
 - Computing posterior matrices.
 - Computation allocated took 0.05 seconds.
Warning message:
In calc_lik_matrix(data, Ulist, log = TRUE, algorithm.version = algorithm.version) :
  Some mixture components result in non-finite likelihoods, either
 due to numerical underflow/overflow, or due to covariance matrices
 that are not s.p.d.: 54, 59, 64, 69, 74 
```

One change that might help here is a way to relate the numbers `54, 59, 64, 69, 74` to the five matrices that I entered. There are 4 traits and 5 matrices, so I'm not sure why there are 76 mixture components, or how to determine which of the 5 matrices is causing the issue (assuming I understand what's going on here).

**Comment by pcarbo** [comment]
@lukeholman Can you check that the weights (pi's) corresponding to these components are zero? They should be. (@gaow This might be a good test to include, if you don't have that already.)

@gaow Is there a simple way to determine the relationship between the mixture components and the scale factors / covariance matrices?

SPD = symmetric positive definite (at least that's what it should mean), which is not the same as being semidefinite.

**Comment by stephens999** [comment]
the warning is misleading to use SPD since the matrices do not need to be positive definite.
Only symmetric positive semi-definite.

it looks like the problem is with the ED routine... ideally we should improve the routine!

**Comment by pcarbo** [comment]
@stephens999 I thought it was pretty clear because I'm referring to the covariance matrices for the individual mixture components, but if you have suggestions for making the message more clear, I'm happy to incorporate your suggestions.

**Comment by stephens999** [comment]
the mixture components in the prior (U) or the marginal likelihood (U+V) ?

**Comment by pcarbo** [comment]
@stephens999 Mixture components in the marginal likelihood.

This also relates to the question I had (above) for Gao:

> Is there a recommended way to determine the relationship between the mixture components and the scale factors / covariance matrices?

**Comment by stephens999** [comment]
what I was saying is that in mashr when we refer to "covariance matrices" we usually mean in the prior, not in the marginal likelihood. So this usage is confusing.

**Comment by stephens999** [comment]
how about just "invalid covariance matrices"

this is vaguer, but less technical, and in any case we don't actually currently check whether 
V+U is spd or not...

(I'm particularly trying to avoid anything that might inadvertently
suggest to the user that the Us have to be SPD,
since they do not and indeed most of our canonical Us are not SPD!)

**Comment by pcarbo** [comment]
> how about just "invalid covariance matrices"

@stephens999 Okay! Changed.

> (I'm particularly trying to avoid anything that might inadvertently suggest to the user that the Us have to be SPD, since they do not and indeed most of our canonical Us are not SPD!)

I agree, and I wasn't sure how to achieve that in the warning message.

> This is vaguer, but less technical, and in any case we don't actually currently check whether
V+U is spd or not...

That is true, but when we obtain infinite likelihoods it is most likely because the U + V matrices are not spd, hence the warning.

**Comment by lukeholman** [comment]
> @lukeholman Can you check that the weights (pi's) corresponding to these components are zero? They should be. (@gaow This might be a good test to include, if you don't have that already.)
> 
> @gaow Is there a recommended way to determine the relationship between the mixture components and the scale factors / covariance matrices?
> 
> SPD = symmetric positive definite (at least that's what it should mean), which is not the same as being semidefinite.

**Comment by lukeholman** [comment]
Whoops, sorry I clicked the wrong thing and 'closed' the issue, when trying to reply to @pcarbo. Not sure how to re-open it (the button says "Open new issue") so I'm just going to leave it to avoid doing more damage.

You asked "Can you check that the weights (pi's) corresponding to these components are zero? They should be. ", and the answer is yes:

```
Warning message:
In calc_lik_matrix(data, Ulist, log = TRUE, algorithm.version = algorithm.version) :
  Some mixture components result in non-finite likelihoods, either
 due to numerical underflow/overflow, or due to covariance matrices
 that are not s.p.d.: 4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74 

> TWAS_ED$fitted_g$pi[c(4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74 )]
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by lukeholman** [comment]
Hi there,

I'm back working on this data again after about a year! Last time, I think you made some changes based on the issues in this thread, and I updated mashr to try again. The analysis I ran before no longer runs (same code), and so I started trouble-shooting. 

Basically when running `mash()` on some data (beta and SE from a GWAS of 4 traits) using the canonical mode, I get this error (I cropped off hundreds more `chol()` warnings):

```
warning: chol(): given matrix is not symmetric

error: chol(): decomposition failed

warning: chol(): given matrix is not symmetric

error: chol(): decomposition failed
 - Likelihood calculations took 0.08 seconds.
 - Fitting model with 145 mixture components.
Error in verify.likelihood.matrix(L) : 
  Input argument "L" should be a numeric matrix with >= 2 columns, >= 1 rows, all its entries should be non-negative, finite and not NA, and some entries should be positive
Calls: %>% ... do.call -> mixSQP -> <Anonymous> -> verify.likelihood.matrix
```

That error from `verify.likelihood.matrix(L)` refers to an internal function from `mixSQP`, I think. I get this message whatever covariance matrix I supply, e.g. the ones from `cov_canonical`, so I suspect it's a problem with the structure of my data, and not the U matrices I am supplying. I guess the likelihood matrix picks up some negative or NA values somewhere, causing this error. 

Any ideas much appreciated! I guess just going back to the old mashr is a bad idea :)

**Comment by lukeholman** [comment]
Thanks for the quick replies. I ran with mixIP method as suggested, and get this new error:

```
error: chol(): decomposition failed

warning: chol(): given matrix is not symmetric

error: chol(): decomposition failed
 - Likelihood calculations took 0.35 seconds.
 - Fitting model with 676 mixture components.
Error in REBayes::KWDual(A, rep(1, k), normalize(w), control = control) : 
  Mosek error:  MSK_RES_ERR_INVALID_AIJ: a[i,j] contains an invalid floating point value, i.e. a NaN or an infinite value.
Calls: %>% ... system.time -> optimize_pi -> do.call -> mixIP -> <Anonymous>
```

I can supply some data and code soon if you like, assuming this new error does not pinpoint the problem?

**Comment by pcarbo** [comment]
@lukeholman This tells us that the error is not specific to the solver (as I suspected) but we would need a runnable example to determine the root cause.

**Comment by lukeholman** [comment]
Hi there,

When I was preparing the data to reply to this thread, I found that there was one row of my data for which the beta and SE estimate was NA - when I removed that one problematic SNP locus,  the mashr problems disappeared. So I reckon the best fix for this would be to add a check to `mash_set_data()` and/or `mash()` for NAs, NaNs etc in the input data, and return a warning or an error, so it's easier to catch for people like me that assumed PLINK was doing what I thought! 

Many thanks

**Comment by pcarbo** [comment]
Glad you solved your problem. And great suggestion!
