### ISSUE TITLE
Apparent bug when using outputlevel = 3

### ISSUE THREAD

**Issue by lukeholman** [stephenslab/mashr#44]
Reproduce it with:
```
simdata = simple_sims(500, 5, 1)
data = mash_set_data(simdata$Bhat, simdata$Shat)
U.c = cov_canonical(data)  
res.mash = mash(data, U.c, outputlevel = 3)
```

This gives the output:
```
 - Computing 2000 x 151 likelihood matrix.
 - Likelihood calculations took 0.03 seconds.
 - Fitting model with 151 mixture components.
 - Model fitting took 4.06 seconds.
 - Computing posterior matrices.
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
```

I had a quick look, and I think the bug can be traced to `compute_posterior_matrices()`, specifically this part where the dim names are assigned:

```
for (i in names(posterior_matrices)) {
            if (!is.null(colnames(data$Bhat))) 
                colnames(posterior_matrices[[i]]) <- colnames(data$Bhat)
            if (!is.null(rownames(data$Bhat))) 
                rownames(posterior_matrices[[i]]) <- rownames(data$Bhat)
        }
```

When one selects `outputlevel = 3`, the final element of the list `posterior_matrices` is a 3D array (rather than a matrix like the other elements), and so R doesn't like it when one tries to assign row and column names.

**Comment by gaow** [comment]
Thank you @lukeholman for reporting with a reproducible example! The bug has been fixed in current `master` (along with #42 , `mashr` version 0.2-13).
