### ISSUE TITLE
issue with R=1

### ISSUE THREAD

**Issue by stephens999** [stephenslab/mashr#5]
mashr should work with R=1, but currently does not (at least not dev branch):

```
Shat = matrix(rep(1,10),ncol=1)
Bhat = matrix(rnorm(10),ncol=1) # create some simulated data
data = mashr::set_mash_data(Bhat,Shat)
Ulist = list(id=matrix(1,nrow=1))
res.mash = mashr::mash(data,Ulist)
```

 - Computing 10 x 12 likelihood matrix.
 - Likelihood calculations allocated 0.00 MB and took 0.01 seconds.
 - Computing 10 x 12 likelihood matrix in C++.
 - Likelihood calculations via Armadillo allocated 0.00 MB and took 0.00 seconds.
[1] "Is result equal between R and C++?"        
[2] "Modes of target, current: function, list"  
[3] "target, current do not match when deparsed"
 - Fitting model with 12 mixture components.
Error in lm$lik_matrix : object of type 'closure' is not subsettable

**Comment by stephens999** [comment]
update - this does seem to run ok on master branch

**Comment by gaow** [comment]
I ended up implementing separate univeriate version for likelihood / posterior because it seems a waste to do all those matrix operations on 1X1 matrix.  On your toy example results agree between R and C++:

```r
> Shat = matrix(rep(1,10),ncol=1)
> Bhat = matrix(rnorm(10),ncol=1) # create some simulated data
> data = mashr::set_mash_data(Bhat,Shat)
> Ulist = list(id=matrix(1,nrow=1))
> res.mash = mashr::mash(data,Ulist)
 - Computing 10 x 11 likelihood matrix.
 - Likelihood calculations allocated 0.15 MB and took 0.03 seconds.
 - Computing 10 x 11 likelihood matrix in C++.
 - Likelihood calculations via Armadillo allocated 0.00 MB and took 0.00 seconds.
[1] "Is result equal between R and C++?" "TRUE"                              
 - Fitting model with 11 mixture components.
 - Model fitting allocated 0.50 MB and took 0.08 s.
 - Computing posterior matrices.
 - Computation allocated 0.04 MB and took 0.02 seconds.
 - Computing posterior matrices in C++.
 - C++ Computation allocated 0.01 MB and took 0.00 seconds.
[1] "Is result equal between R and C++?" "TRUE"                
```
Would be interesting to see how it compares in speed with `ashr`.

**Comment by pcarbo** [comment]
@gaow I think the point is that `ashr` with normal likelihood and prior is a special case of `mashr`, so if the result is not the same, then this indicates that there is a bug somewhere.

**Comment by gaow** [comment]
Fixed and informally tested.
