### ISSUE TITLE
Complaint about matrix size

### ISSUE THREAD

**Issue by QinqinHuang** [stephenslab/mashr#69]
Hi,

I was trying to fit the mash model, and had this error:
``` 
- Computing 39972291 x 111 likelihood matrix.

error: Mat::init(): requested size is too large
Error in calc_lik_rcpp(t(data$Bhat), t(data$Shat), data$V, matrix(0, 0,  :
  Mat::init(): requested size is too large
```

I was trying to identify shared eQTL signals across four conditions. The full eQTL summary datasets have almost 40 million tests. I guess the issue is not with the tool but my matrix is too large. Should I do LD thinning and remove some redundant tests/SNPs? What are the sizes that are likely to be handled by the mash model?

Many thanks,
Qinqin

**Comment by gaow** [comment]
A quick check, could you try 'algorithm = "R" ' and see what happens?

**Comment by QinqinHuang** [comment]
Thanks! Do you mean just run
    algorithm = "R" 
in my R session before fitting the model?

I tried and It still gave me the same error.

**Comment by gaow** [comment]
@QinqinHuang I meant to say using `algorithm = "R"` in `mash()` function call, `mash(..., algorithm = "R", ...)` but I suspect R cannot handle that large data either. It would be good if you can reduce the number. There is no need to use that many tests to build MASH model. In our eQTL application we used <20,000 to learn patterns of sharing ('strong' set) and <40,000 to learn the mixture model ('random' set).

**Comment by QinqinHuang** [comment]
Hi Gao,

It seems to do the trick. I will give it some more time.

Thanks! I just realised that I don't really need to use my full data (whole-genome cis-eQTL scan). I can restrict the input to loci with eQTL signals or tests involving eGenes. 

Thanks a lot for your help!

**Comment by stephens999** [comment]
you must be careful with restricting input ...
see the eqtl vignette:
https://github.com/stephenslab/mashr/blob/master/vignettes/eQTL_outline.Rmd

**Comment by QinqinHuang** [comment]
Thanks! That is very useful. I must admit that didn't read all the vignettes though... 
I was using top eQTL SNPs for eGenes in any condition as the "strong set" and didn't do a random subsampling. I was just wondering, if I use all tests (all SNPs within the 2-Mb cis window including the non-significant ones) of eGenes, would there be enough null tests for mash to be trained on? Even we focus on only eGenes, significant cis-eQTL SNPs are still relatively sparse (based on my experience which might be wrong) given that the cis window is not small and the signals are not necessarily active in all conditions, but sure it would be more enriched for significant signals compared with a random subset.

**Comment by gaow** [comment]
@QinqinHuang in GTEx analysis in MASH paper, we set up the  "strong" set as the gene-snp pair having smallest p-value in a gene for <20,000 genes. We then randomly pick 2 to 3 SNPs from each gene to come up with a "random" set of <40,000 SNPs to learn the mixture model. That was enough for our eQTL application. We have a pipeline to do it: 

https://github.com/stephenslab/gtexresults/blob/master/workflows/fastqtl_to_mash.ipynb

but it looks you've already got your data in R so it should be easy for u to subset from there.

**Comment by QinqinHuang** [comment]
Thank you both for your help! 
I am sorry – I was a bit confused because I didn't realise that I could fit the model using a small random subset of the tests, and then estimate posterior probabilities for **other tests** (strong set or any other subsets) that are not necessarily in the previous random subset.

**Comment by harrsha4** [comment]
Hello, 
     Just as a followup to this thread, when you say the strong set was the lead eQTL for 20,000, do you mean within a tissue or amongst all tissues considering you were training on GTEx data? I am currently working with fastqtl results from 5 conditions and used all lead SNP-eGenes from each condition (13,000 X 5 = 65,000) with a 1 million random subset.
