### ISSUE TITLE
Performance benchmarking?

### ISSUE THREAD

**Issue by t-silvers** [stephenslab/mashr#72]
Hi, Related to #71 and #23, I'm using mash on a large eQTL analysis and have some performance questions.

Have you performed any benchmarking (execution time, CPU time, max RAM, etc.) on differently composed data sets + analyses? Apologies if I've missed it somewhere in the paper or repo.

Thanks!

**Comment by gaow** [comment]
Taking an example from #87, 

```r
dim(data$Bhat)
# 4019906    5
```

so we have J = 4 million effects over R = 5 conditions.

To fit MASH model,

```r
timing <- system.time(m.ed <- mash(data,U.ed,outputlevel = 1))
print(timing)
```

```
 - Computing 4019906 x 157 likelihood matrix.
 - Likelihood calculations took 881.09 seconds.
 - Fitting model with 157 mixture components.
 - Model fitting took 802.35 seconds.
     user    system   elapsed 
11868.635  1336.566  1726.421 
```

Peak memory is about 32GB. 

In our paper (Urbut et al 2019) we fitted MASH with J < 100K effects (sufficient for ) over R ~= 50 conditions. The time complexity is linear in J and quadratic in R so the above example can give you some idea on how much time it may take to run a GTEx-like MASH fit.

To compute posterior quantities for 10K effects,

```r
subset = 1e4
rows <- sample(nrow(data$Bhat),subset)
data2 <- mash_set_data(data$Bhat[rows,],data$Shat[rows,])
timing <- system.time(out <- mash_compute_posterior_matrices(g = m.ed,data = data2))
print(timing)
```

```  
  user  system elapsed 
  4.010   0.005   4.015 
```

100K effects,

```r
subset = 1e5
rows <- sample(nrow(data$Bhat),subset)
data2 <- mash_set_data(data$Bhat[rows,],data$Shat[rows,])
timing <- system.time(out <- mash_compute_posterior_matrices(g = m.ed,data = data2))
print(timing)
```

```
   user  system elapsed 
 50.257   0.328  50.585 
```

1 million effects,

```r
subset = 1e6
rows <- sample(nrow(data$Bhat),subset)
data2 <- mash_set_data(data$Bhat[rows,],data$Shat[rows,])
timing <- system.time(out <- mash_compute_posterior_matrices(g = m.ed,data = data2))
print(timing)
```

```
   user  system elapsed 
517.510   5.479 522.995 
```

And as discussed in #87 you can always chunk the data into batches and use multiple compute nodes to generate posterior effects.
