### ISSUE TITLE
trouble installing mashr 

### ISSUE THREAD

**Issue by annacuomo** [stephenslab/mashr#73]
seems to require ashr, and needs mixsqp when installing ashr 

ERROR: dependency ‘mixsqp’ is not available for package ‘ashr’

R.Version is 3.6.2

installation is done as follows:

install.packages("devtools")
devtools::install_github("stephenslab/mashr@v0.2-11")

**Comment by pcarbo** [comment]
@annacuomo Apologies, and thanks for your interest in mashr. For now, pleasee install mixsqp from [GitHub](https://github.com/stephenslab/mixsqp):

```R
library(devtools)
install_github("stephenslab/mixsqp")
```

**Comment by annacuomo** [comment]
Thanks,

But I get an error installing that as well?

clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘mixsqp’

**Comment by pcarbo** [comment]
@annacuomo You will need to compile the mixsqp package from source while it is unavailable on CRAN. For this, you will need to download the appropriate C/Fortran compilers, and edit your `Makevars` file. Fortunately, the R website has good instructions for how to do this; e.g., if you have a Mac (which I think you do based on the error message), the instructions are given [here](https://cran.r-project.org/bin/macosx/tools).

I've written [additional instructions](https://github.com/pcarbo/pcarbo/blob/master/docs/r-macos.md) that may be helpful

You will need these compilers anyhow to install mashr.

**Comment by pcarbo** [comment]
@annacuomo mixsqp is now back on CRAN, and we are working on getting ashr up there. I'm closing this ticket. Apologies for the inconvenience.
