### ISSUE TITLE
Error in Fitting mash model

### ISSUE THREAD

**Issue by mural123** [stephenslab/mashr#75]
Hi, I am trying to fit mash model to my data from association studies. I am following all the steps described in https://stephenslab.github.io/mashr/articles/eQTL_outline.html. I am running into a particular issue mentioned below. I am assuming it has to do with the large matrix of data I have, as the subset did work just fine but when I increase the number of conditions I encounter this problem. Can some one please explain the problem here and how to fix it?

Thank you
##########################
m = mash(data.random, Ulist = c(U.ed,U.c), outputlevel = 1)

Computing 20000 x 2554 likelihood matrix.
Likelihood calculations took 9017.15 seconds.
Fitting model with 2554 mixture components.
Error in if (all(y > 0)) return(-sum(w * (z + log(y)))) else return(Inf) :
missing value where TRUE/FALSE needed
Calls: mash ... optimize_pi -> do.call -> mixSQP -> -> mixobj
Timing stopped at: 518.4 30.56 152
Execution halted
################

**Comment by mural123** [comment]
Hi, I am trying to fit mash model to my data from association studies. I am following all the steps described in https://stephenslab.github.io/mashr/articles/eQTL_outline.html. I am running into a particular issue mentioned below. I am assuming it has to do with the large matrix of data I have, as the subset did work just fine but when I increase the number of conditions I encounter this problem. Can some one please explain the problem here and how to fix it?

Thank you
##########################
m = mash(data.random, Ulist = c(U.ed,U.c), outputlevel = 1)
 - Computing 20000 x 2554 likelihood matrix.
 - Likelihood calculations took 9017.15 seconds.
 - Fitting model with 2554 mixture components.
Error in if (all(y > 0)) return(-sum(w * (z + log(y)))) else return(Inf) : 
  missing value where TRUE/FALSE needed
Calls: mash ... optimize_pi -> do.call -> mixSQP -> <Anonymous> -> mixobj
Timing stopped at: 518.4 30.56 152
Execution halted
################

**Comment by willwerscheid** [comment]
I'm pretty sure this is coming from `mixsqp` -- I independently came across the same error. I've opened an issue over there: https://github.com/stephenslab/mixsqp/issues/39.

**Comment by pcarbo** [comment]
@mural123 @willwerscheid Please try running `mashr` again with the latest version of mixsqp.

**Comment by mural123** [comment]
Hi @pcarbo Thank you for fixing the issue. Fitting mash model works now but now I am facing new error. I tried reducing number of random subset and also increased the memory but it did not help and I am getting this error. Can you please explain me what could be the issue here and how to fix it?

> # Data driven covariances
> U.pca = cov_pca(data.strong,5)
> U.ed = cov_ed(data.strong, U.pca)

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: extreme_deconvolution_rcpp(ydata, tycovar, projection, logweights,     xamp, xmean, unlist(lapply(xcovar, t)), fixamp, fixmean,     fixcovar, tol, maxiter, likeonly, w, clog, splitnmerge, clog2,     noprojection, diagerrors, noweight)
 2: extreme_deconvolution(data$Bhat[subset, ], ycovar, xamp = pi_init,     xmean = matrix(0, nrow = K, ncol = R), xcovar = Ulist_init,     fixmean = TRUE, ...)
 3: ed_wrapper(data, Ulist_init, subset, ...)
 4: cov_ed(data.strong, U.pca)
An irrecoverable exception occurred. R is aborting now ...

**Comment by gaow** [comment]
@mural123 this might be related to #76 which another user has submitted a patch that i just merged. Would you mind updating to the current `master` of `mashr` and give it a go?

**Comment by YushaLiu** [comment]
@mural123 @gaow I had exactly the same error on my dataset, but with pull #76 this error disappears now. Please update to the latest version of mashr and try again.

**Comment by pcarbo** [comment]
@gaow What was the fix?

**Comment by gaow** [comment]
@pcarbo here is the patch:

https://github.com/stephenslab/mashr/commit/026377a74701bdeff16c6283c79e6156d37ca70b

and my comment to the PR:

https://github.com/stephenslab/mashr/pull/76#issuecomment-605090892

But if @YushaLiu ran into the problem then her data would be a great test case for your new ED work -- we should keep that in mind!

**Comment by gaow** [comment]
@mural123 I'll consider the issue resolved but please feel free to reopen the ticket or use a new one if you have other issues.
