### ISSUE TITLE
` profmem::profmem` function hides error message from profiled routine

### ISSUE THREAD

**Issue by gaow** [stephenslab/mashr#8]
This behavior is inconvenient because it hides error status of the function, causing downstream procedures to fail and display error messages not directly relevant to where it actually fails. If there is no way to show error message and quit properly when `profmem` is used, then at least we should have a `debug` switch in the function call, or, I do not mind tying it with some verbosity level.

**Comment by pcarbo** [comment]
@gaow `profmem` is only being used for testing; we should remove it once we are happy with the `Rcpp` implementation.

**Comment by gaow** [comment]
Made `profmem` optional anyways with default `false`, because it has computational overhead.
