### ISSUE TITLE
What does a negative local false sign rate mean?

### ISSUE THREAD

**Issue by arider2** [stephenslab/mashr#84]
Hi, 

When I run get_lfsr on my mash analysis I see some negative local false sign rates. Does this indicate some mistake by me or is their a meaning to these?

See below in the first column:

`x <- get_lfsr(m2)`
`(x) <- c(1:ncol(x))`
`(x) <- c(1:nrow(x))`
`rownames(x) <- paste0("effect_",rownames(x))`
`colnames(x) <- paste0("con_",colnames(x))`
`y <- as.data.frame(x)`
`y <- y[order(y$con_1, decreasing = F),]`
`y[1:5, 1:5]`

con_1 con_2         con_3         con_4       con_5
effect_9  -2.220446e-16     0 -2.220446e-16 -2.220446e-16 6.01097e-07
effect_10 -2.220446e-16     0 -2.220446e-16 -2.220446e-16 6.01097e-07
effect_11 -2.220446e-16     0 -2.220446e-16 -2.220446e-16 6.01097e-07
effect_12 -2.220446e-16     0 -2.220446e-16 -2.220446e-16 6.01097e-07
effect_13 -2.220446e-16     0 -2.220446e-16 -2.220446e-16 6.01097e-07

**Comment by stephens999** [comment]
Do you have the latest version of ashr? This problem should be fixed in
latest version.

**Comment by arider2** [comment]
if the latest version is 2.2-47 then yes I do.

**Comment by arider2** [comment]
Thanks for your quick reply. I installed from CRAN so I don't think I'm up to date. I'll install from GitHub and try again.

**Comment by arider2** [comment]
Installing from GitHub resolved the issue. Thank you.
