### ISSUE TITLE
Formal Extreme Deconvolution wrapper

### ISSUE THREAD

**Issue by gaow** [stephenslab/mashr#9]
Related to #7: move `extreme_deconv` to a separate repo. It is not likely Bovy is updating it any more, so it may warrant to create a "frozen" R version to support `mashr` (my R wrapper to Bovy is dynamic that can potentially incorporate his future changes to code). I can take a first step to set it up if @pcarbo creates a repo for it.

**Comment by pcarbo** [comment]
@gaow What do you think about including the `ExtremeDeconvolution` source code inside the `mashr` package?

**Comment by gaow** [comment]
Hmm it maybe a good idea ... although it may (or may not) be some work to integrate it with our Rcpp / RcppArmadillo framework. Currently it is not done in Rcpp.

**Comment by pcarbo** [comment]
@gaow Not a problem. `Rcpp` is basically just "synactic sugar" for the `.Call` interface, which is what `ExtremeDeconvolution` uses. My varbvs package uses `Rcpp` and directly calls the `.Call` interface.

In any case, I suggest not making this a high priority right now until we are comfortable with the initial implementation using `Rcpp`.

**Comment by stephens999** [comment]
I'm fine with putting it in its own repo to make installation easier etc. I'll just note that our use of ED in mash may ultimately be superseded by other approaches. So not worth investing *too* much time in right now.

**Comment by pcarbo** [comment]
> I'll just note that our use of ED in mash may ultimately be superseded by other approaches. So not worth investing too much time in right now.

I agree.

**Comment by stephens999** [comment]
i'm closing this for now. going to start a different issue on superceding ED
