### ISSUE TITLE
Local false sign rate of 0?

### ISSUE THREAD

**Issue by crvcheet21** [stephenslab/mashr#92]
Hi, 

Should I be suspicious of local false sign rates of zero? I noticed some of these when getting Inf values from -log10(lfsr).

Apologies if I've missed some documentation on this.

Thank you!

**Comment by pcarbo** [comment]
No, LFSRs of zero are (numerically) indistinguishable from very small LFSRs. This is similar to the situation for p-value calculations, where it can be difficult to distinguish between a p-value of zero and a very small p-value.

**Comment by crvcheet21** [comment]
Thanks!
