### ISSUE TITLE
maybe we should not output lfdr?

### ISSUE THREAD

**Issue by stephens999** [stephenslab/mashr#93]
in results we do output a matrix of lfdr values. These will tend to be sensitive to misestimated covariance
matrices, and generally we would not recommend users to use them - they should use the lfsr.
The vignettes all encourage use of lfsr, and never mention lfdr but people nonetheless will see the lfdr if

they look at names(results). 
Maybe we should not even be outputting them, at least by default.
(If we need them for testing purposes we could add a flag and tell people not to use it in the documentation...)

**Comment by pcarbo** [comment]
@stephens999 Shouldn't we be consistent with what `ashr` does? `ashr::ash` outputs both `lfdr` and `lfsr` [and `help(ash)` does not provide guidance on this].

**Comment by stephens999** [comment]
the issue i'm worrying about is that lfdr is even more sensitive to prior for mash than for ash... so in ash lfdr is arguably
often ok. for mash i would tend never to use it.

**Comment by pcarbo** [comment]
@stephens999 I added a new argument, `mash(..., output_lfdr = FALSE)`. This is what `help(mash)` now says:

```
output_lfdr: If output_lfdr = TRUE, output local false discovery rate estimates. The lfdr tends to be 
sensitive to mis-estimated covariance matrices, and generally we do not recommend using them; 
we recommend using the local false sign rate (lfsr) instead, which is always returned, even when 
output_lfdr = TRUE.
```

**Comment by stephens999** [comment]
looks great, thank you!
